### ISSUE TITLE
yarn install failed

### ISSUE THREAD

**Issue by guotie** [Premian-Labs/premia-contracts#3]
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: mainnet - Expected string, received undefined
  * Invalid account: #0 for network: rinkeby - Expected string, received undefined
  * Invalid account: #0 for network: kovan - Expected string, received undefined
  * Invalid account: #0 for network: ropsten - Expected string, received undefined
  * Invalid account: #0 for network: arbitrum - Expected string, received undefined
  * Invalid account: #0 for network: rinkebyArbitrum - Expected string, received undefined

**Comment by Lumyo** [comment]
@guotie You most likely have not set the necessary environment variables
