### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by rotcivegaf** [Premian-Labs/premia-contracts#6]
The https:/premia.finance link, go to https://github.com/premia.finance and not to https://premia.finance/

Also the name miss one `/`, from: `https:/premia.finance` to `https://premia.finance/` 

![image](https://user-images.githubusercontent.com/7088778/229209596-e108d82e-ef6f-47ff-b3ac-5ffb5d1adf0f.png)

**Comment by Lumyo** [comment]
Fixed ! Thanks for reporting this ! :)
